version: '3.8'


services:
  temporal-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production.local
    volumes:
      - ./certs:/certs
    ports:
      - "9555:9555"